<?php
/**
 * Created by PhpStorm.
 * User: nj
 * Date: 16/8/29
 * Time: 17:35
 */
class emailException extends Exception {

}

class pwdException extends Exception {
    function __toString()
    {
        parent::__toString(); // TODO: Change the autogenerated stub
        return "Exception {$this->getCode()}:{$this->getMessage()}
        in File():{$this->getFile()} online {$this->getLine()}";
    }
}

function reg($reginfo){
    if(empty($reginfo)||!isset($reginfo)){
        throw new Exception('param error');
    }

    if(empty($reginfo['email'])){
        throw new emailException('empty email');
    }

    if(empty($reginfo['pwd'])){
        throw new pwdException('pwd error');
    }
}

try{
    reg(array('pwd'=>'test@qq.com'));
}catch (emailException $e){
    echo $e->getMessage();
    echo "<br/> after deal";
}catch (pwdException $ee){
    echo $ee;
    echo "<br/> after deal";
}catch (Exception $eee){
    echo $eee->getTraceAsString();
}